// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: setup.proto

package setup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrganizationConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrganizationConfigRequest) Reset() {
	*x = OrganizationConfigRequest{}
	mi := &file_setup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationConfigRequest) ProtoMessage() {}

func (x *OrganizationConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationConfigRequest.ProtoReflect.Descriptor instead.
func (*OrganizationConfigRequest) Descriptor() ([]byte, []int) {
	return file_setup_proto_rawDescGZIP(), []int{0}
}

func (x *OrganizationConfigRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type SetupOrganizationResponse struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	OrganizationId        string                  `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationName      string                  `protobuf:"bytes,2,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	OrganizationCode      string                  `protobuf:"bytes,3,opt,name=organization_code,json=organizationCode,proto3" json:"organization_code,omitempty"`
	OrganizationReference *structpb.Struct        `protobuf:"bytes,4,opt,name=organization_reference,json=organizationReference,proto3" json:"organization_reference,omitempty"`
	OrganizationType      string                  `protobuf:"bytes,5,opt,name=organization_type,json=organizationType,proto3" json:"organization_type,omitempty"`
	BrandName             string                  `protobuf:"bytes,6,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	BrandLogoUrl          string                  `protobuf:"bytes,7,opt,name=brand_logo_url,json=brandLogoUrl,proto3" json:"brand_logo_url,omitempty"`
	Industry              string                  `protobuf:"bytes,8,opt,name=industry,proto3" json:"industry,omitempty"`
	IndustrySubType       *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=industry_sub_type,json=industrySubType,proto3" json:"industry_sub_type,omitempty"`
	OrgSecretKey          *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=org_secret_key,json=orgSecretKey,proto3" json:"org_secret_key,omitempty"`
	ComplianceInfo        *structpb.Struct        `protobuf:"bytes,11,opt,name=compliance_info,json=complianceInfo,proto3" json:"compliance_info,omitempty"`
	BusinessSegment       *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=business_segment,json=businessSegment,proto3" json:"business_segment,omitempty"`
	BusinessOrigin        *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=business_origin,json=businessOrigin,proto3" json:"business_origin,omitempty"`
	EnableMfa             bool                    `protobuf:"varint,14,opt,name=enable_mfa,json=enableMfa,proto3" json:"enable_mfa,omitempty"`
	MfaType               *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=mfa_type,json=mfaType,proto3" json:"mfa_type,omitempty"`
	MfaSubType            *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=mfa_sub_type,json=mfaSubType,proto3" json:"mfa_sub_type,omitempty"`
	StartDate             *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate               *wrapperspb.StringValue `protobuf:"bytes,18,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	DateOfIncorporation   *wrapperspb.StringValue `protobuf:"bytes,19,opt,name=date_of_incorporation,json=dateOfIncorporation,proto3" json:"date_of_incorporation,omitempty"`
	Timezone              *wrapperspb.StringValue `protobuf:"bytes,20,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CreatedAtLocal        string                  `protobuf:"bytes,21,opt,name=created_at_local,json=createdAtLocal,proto3" json:"created_at_local,omitempty"`
	CreatedAtUtc          string                  `protobuf:"bytes,22,opt,name=created_at_utc,json=createdAtUtc,proto3" json:"created_at_utc,omitempty"`
	UpdatedAtLocal        *wrapperspb.StringValue `protobuf:"bytes,23,opt,name=updated_at_local,json=updatedAtLocal,proto3" json:"updated_at_local,omitempty"`
	UpdatedAtUtc          *wrapperspb.StringValue `protobuf:"bytes,24,opt,name=updated_at_utc,json=updatedAtUtc,proto3" json:"updated_at_utc,omitempty"`
	DemoMode              bool                    `protobuf:"varint,25,opt,name=demo_mode,json=demoMode,proto3" json:"demo_mode,omitempty"`
	IsActive              int32                   `protobuf:"varint,26,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SetupOrganizationResponse) Reset() {
	*x = SetupOrganizationResponse{}
	mi := &file_setup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupOrganizationResponse) ProtoMessage() {}

func (x *SetupOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupOrganizationResponse.ProtoReflect.Descriptor instead.
func (*SetupOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_setup_proto_rawDescGZIP(), []int{1}
}

func (x *SetupOrganizationResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SetupOrganizationResponse) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *SetupOrganizationResponse) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *SetupOrganizationResponse) GetOrganizationReference() *structpb.Struct {
	if x != nil {
		return x.OrganizationReference
	}
	return nil
}

func (x *SetupOrganizationResponse) GetOrganizationType() string {
	if x != nil {
		return x.OrganizationType
	}
	return ""
}

func (x *SetupOrganizationResponse) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *SetupOrganizationResponse) GetBrandLogoUrl() string {
	if x != nil {
		return x.BrandLogoUrl
	}
	return ""
}

func (x *SetupOrganizationResponse) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *SetupOrganizationResponse) GetIndustrySubType() *wrapperspb.StringValue {
	if x != nil {
		return x.IndustrySubType
	}
	return nil
}

func (x *SetupOrganizationResponse) GetOrgSecretKey() *wrapperspb.StringValue {
	if x != nil {
		return x.OrgSecretKey
	}
	return nil
}

func (x *SetupOrganizationResponse) GetComplianceInfo() *structpb.Struct {
	if x != nil {
		return x.ComplianceInfo
	}
	return nil
}

func (x *SetupOrganizationResponse) GetBusinessSegment() *wrapperspb.StringValue {
	if x != nil {
		return x.BusinessSegment
	}
	return nil
}

func (x *SetupOrganizationResponse) GetBusinessOrigin() *wrapperspb.StringValue {
	if x != nil {
		return x.BusinessOrigin
	}
	return nil
}

func (x *SetupOrganizationResponse) GetEnableMfa() bool {
	if x != nil {
		return x.EnableMfa
	}
	return false
}

func (x *SetupOrganizationResponse) GetMfaType() *wrapperspb.StringValue {
	if x != nil {
		return x.MfaType
	}
	return nil
}

func (x *SetupOrganizationResponse) GetMfaSubType() *wrapperspb.StringValue {
	if x != nil {
		return x.MfaSubType
	}
	return nil
}

func (x *SetupOrganizationResponse) GetStartDate() *wrapperspb.StringValue {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *SetupOrganizationResponse) GetEndDate() *wrapperspb.StringValue {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *SetupOrganizationResponse) GetDateOfIncorporation() *wrapperspb.StringValue {
	if x != nil {
		return x.DateOfIncorporation
	}
	return nil
}

func (x *SetupOrganizationResponse) GetTimezone() *wrapperspb.StringValue {
	if x != nil {
		return x.Timezone
	}
	return nil
}

func (x *SetupOrganizationResponse) GetCreatedAtLocal() string {
	if x != nil {
		return x.CreatedAtLocal
	}
	return ""
}

func (x *SetupOrganizationResponse) GetCreatedAtUtc() string {
	if x != nil {
		return x.CreatedAtUtc
	}
	return ""
}

func (x *SetupOrganizationResponse) GetUpdatedAtLocal() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedAtLocal
	}
	return nil
}

func (x *SetupOrganizationResponse) GetUpdatedAtUtc() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedAtUtc
	}
	return nil
}

func (x *SetupOrganizationResponse) GetDemoMode() bool {
	if x != nil {
		return x.DemoMode
	}
	return false
}

func (x *SetupOrganizationResponse) GetIsActive() int32 {
	if x != nil {
		return x.IsActive
	}
	return 0
}

type SetupCompanyResponse struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	CompanyId           string                  `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	OrganizationId      string                  `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CompanyName         string                  `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	CompanyReference    *structpb.Struct        `protobuf:"bytes,4,opt,name=company_reference,json=companyReference,proto3" json:"company_reference,omitempty"`
	CompanyType         string                  `protobuf:"bytes,5,opt,name=company_type,json=companyType,proto3" json:"company_type,omitempty"`
	BrandName           *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	Industry            *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=industry,proto3" json:"industry,omitempty"`
	IndustrySubType     *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=industry_sub_type,json=industrySubType,proto3" json:"industry_sub_type,omitempty"`
	ComplianceInfo      *structpb.Struct        `protobuf:"bytes,9,opt,name=compliance_info,json=complianceInfo,proto3" json:"compliance_info,omitempty"`
	StartDate           *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate             *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	DateOfIncorporation *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=date_of_incorporation,json=dateOfIncorporation,proto3" json:"date_of_incorporation,omitempty"`
	Timezone            *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CreatedAtLocal      string                  `protobuf:"bytes,14,opt,name=created_at_local,json=createdAtLocal,proto3" json:"created_at_local,omitempty"`
	CreatedAtUtc        string                  `protobuf:"bytes,15,opt,name=created_at_utc,json=createdAtUtc,proto3" json:"created_at_utc,omitempty"`
	UpdatedAtLocal      *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=updated_at_local,json=updatedAtLocal,proto3" json:"updated_at_local,omitempty"`
	UpdatedAtUtc        *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=updated_at_utc,json=updatedAtUtc,proto3" json:"updated_at_utc,omitempty"`
	DemoMode            bool                    `protobuf:"varint,18,opt,name=demo_mode,json=demoMode,proto3" json:"demo_mode,omitempty"`
	IsActive            int32                   `protobuf:"varint,19,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SetupCompanyResponse) Reset() {
	*x = SetupCompanyResponse{}
	mi := &file_setup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupCompanyResponse) ProtoMessage() {}

func (x *SetupCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupCompanyResponse.ProtoReflect.Descriptor instead.
func (*SetupCompanyResponse) Descriptor() ([]byte, []int) {
	return file_setup_proto_rawDescGZIP(), []int{2}
}

func (x *SetupCompanyResponse) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *SetupCompanyResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SetupCompanyResponse) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *SetupCompanyResponse) GetCompanyReference() *structpb.Struct {
	if x != nil {
		return x.CompanyReference
	}
	return nil
}

func (x *SetupCompanyResponse) GetCompanyType() string {
	if x != nil {
		return x.CompanyType
	}
	return ""
}

func (x *SetupCompanyResponse) GetBrandName() *wrapperspb.StringValue {
	if x != nil {
		return x.BrandName
	}
	return nil
}

func (x *SetupCompanyResponse) GetIndustry() *wrapperspb.StringValue {
	if x != nil {
		return x.Industry
	}
	return nil
}

func (x *SetupCompanyResponse) GetIndustrySubType() *wrapperspb.StringValue {
	if x != nil {
		return x.IndustrySubType
	}
	return nil
}

func (x *SetupCompanyResponse) GetComplianceInfo() *structpb.Struct {
	if x != nil {
		return x.ComplianceInfo
	}
	return nil
}

func (x *SetupCompanyResponse) GetStartDate() *wrapperspb.StringValue {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *SetupCompanyResponse) GetEndDate() *wrapperspb.StringValue {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *SetupCompanyResponse) GetDateOfIncorporation() *wrapperspb.StringValue {
	if x != nil {
		return x.DateOfIncorporation
	}
	return nil
}

func (x *SetupCompanyResponse) GetTimezone() *wrapperspb.StringValue {
	if x != nil {
		return x.Timezone
	}
	return nil
}

func (x *SetupCompanyResponse) GetCreatedAtLocal() string {
	if x != nil {
		return x.CreatedAtLocal
	}
	return ""
}

func (x *SetupCompanyResponse) GetCreatedAtUtc() string {
	if x != nil {
		return x.CreatedAtUtc
	}
	return ""
}

func (x *SetupCompanyResponse) GetUpdatedAtLocal() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedAtLocal
	}
	return nil
}

func (x *SetupCompanyResponse) GetUpdatedAtUtc() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedAtUtc
	}
	return nil
}

func (x *SetupCompanyResponse) GetDemoMode() bool {
	if x != nil {
		return x.DemoMode
	}
	return false
}

func (x *SetupCompanyResponse) GetIsActive() int32 {
	if x != nil {
		return x.IsActive
	}
	return 0
}

type SetupLocationResponse struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	LocationId        string                  `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	OrganizationId    string                  `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CompanyId         string                  `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	LocationName      string                  `protobuf:"bytes,4,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	LocationReference *structpb.Struct        `protobuf:"bytes,5,opt,name=location_reference,json=locationReference,proto3" json:"location_reference,omitempty"`
	LocationType      string                  `protobuf:"bytes,6,opt,name=location_type,json=locationType,proto3" json:"location_type,omitempty"`
	Industry          *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=industry,proto3" json:"industry,omitempty"`
	IndustrySubType   *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=industry_sub_type,json=industrySubType,proto3" json:"industry_sub_type,omitempty"`
	ComplianceInfo    *structpb.Struct        `protobuf:"bytes,9,opt,name=compliance_info,json=complianceInfo,proto3" json:"compliance_info,omitempty"`
	StartDate         *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate           *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Timezone          *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CreatedAtLocal    string                  `protobuf:"bytes,13,opt,name=created_at_local,json=createdAtLocal,proto3" json:"created_at_local,omitempty"`
	CreatedAtUtc      string                  `protobuf:"bytes,14,opt,name=created_at_utc,json=createdAtUtc,proto3" json:"created_at_utc,omitempty"`
	UpdatedAtLocal    *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=updated_at_local,json=updatedAtLocal,proto3" json:"updated_at_local,omitempty"`
	UpdatedAtUtc      *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=updated_at_utc,json=updatedAtUtc,proto3" json:"updated_at_utc,omitempty"`
	DemoMode          bool                    `protobuf:"varint,17,opt,name=demo_mode,json=demoMode,proto3" json:"demo_mode,omitempty"`
	IsActive          int32                   `protobuf:"varint,18,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetupLocationResponse) Reset() {
	*x = SetupLocationResponse{}
	mi := &file_setup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupLocationResponse) ProtoMessage() {}

func (x *SetupLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupLocationResponse.ProtoReflect.Descriptor instead.
func (*SetupLocationResponse) Descriptor() ([]byte, []int) {
	return file_setup_proto_rawDescGZIP(), []int{3}
}

func (x *SetupLocationResponse) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *SetupLocationResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SetupLocationResponse) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *SetupLocationResponse) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *SetupLocationResponse) GetLocationReference() *structpb.Struct {
	if x != nil {
		return x.LocationReference
	}
	return nil
}

func (x *SetupLocationResponse) GetLocationType() string {
	if x != nil {
		return x.LocationType
	}
	return ""
}

func (x *SetupLocationResponse) GetIndustry() *wrapperspb.StringValue {
	if x != nil {
		return x.Industry
	}
	return nil
}

func (x *SetupLocationResponse) GetIndustrySubType() *wrapperspb.StringValue {
	if x != nil {
		return x.IndustrySubType
	}
	return nil
}

func (x *SetupLocationResponse) GetComplianceInfo() *structpb.Struct {
	if x != nil {
		return x.ComplianceInfo
	}
	return nil
}

func (x *SetupLocationResponse) GetStartDate() *wrapperspb.StringValue {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *SetupLocationResponse) GetEndDate() *wrapperspb.StringValue {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *SetupLocationResponse) GetTimezone() *wrapperspb.StringValue {
	if x != nil {
		return x.Timezone
	}
	return nil
}

func (x *SetupLocationResponse) GetCreatedAtLocal() string {
	if x != nil {
		return x.CreatedAtLocal
	}
	return ""
}

func (x *SetupLocationResponse) GetCreatedAtUtc() string {
	if x != nil {
		return x.CreatedAtUtc
	}
	return ""
}

func (x *SetupLocationResponse) GetUpdatedAtLocal() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedAtLocal
	}
	return nil
}

func (x *SetupLocationResponse) GetUpdatedAtUtc() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedAtUtc
	}
	return nil
}

func (x *SetupLocationResponse) GetDemoMode() bool {
	if x != nil {
		return x.DemoMode
	}
	return false
}

func (x *SetupLocationResponse) GetIsActive() int32 {
	if x != nil {
		return x.IsActive
	}
	return 0
}

type SetupFeatureAccessResponse struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	AccessId       string                  `protobuf:"bytes,1,opt,name=access_id,json=accessId,proto3" json:"access_id,omitempty"`
	OrganizationId string                  `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	FeatureId      string                  `protobuf:"bytes,3,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	SubFeatureId   string                  `protobuf:"bytes,4,opt,name=sub_feature_id,json=subFeatureId,proto3" json:"sub_feature_id,omitempty"`
	Scopes         *structpb.Struct        `protobuf:"bytes,5,opt,name=scopes,proto3" json:"scopes,omitempty"`
	CreatedAtLocal string                  `protobuf:"bytes,6,opt,name=created_at_local,json=createdAtLocal,proto3" json:"created_at_local,omitempty"`
	CreatedAtUtc   string                  `protobuf:"bytes,7,opt,name=created_at_utc,json=createdAtUtc,proto3" json:"created_at_utc,omitempty"`
	UpdatedAtLocal *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=updated_at_local,json=updatedAtLocal,proto3" json:"updated_at_local,omitempty"`
	UpdatedAtUtc   *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=updated_at_utc,json=updatedAtUtc,proto3" json:"updated_at_utc,omitempty"`
	DemoMode       bool                    `protobuf:"varint,10,opt,name=demo_mode,json=demoMode,proto3" json:"demo_mode,omitempty"`
	IsActive       int32                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetupFeatureAccessResponse) Reset() {
	*x = SetupFeatureAccessResponse{}
	mi := &file_setup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupFeatureAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupFeatureAccessResponse) ProtoMessage() {}

func (x *SetupFeatureAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupFeatureAccessResponse.ProtoReflect.Descriptor instead.
func (*SetupFeatureAccessResponse) Descriptor() ([]byte, []int) {
	return file_setup_proto_rawDescGZIP(), []int{4}
}

func (x *SetupFeatureAccessResponse) GetAccessId() string {
	if x != nil {
		return x.AccessId
	}
	return ""
}

func (x *SetupFeatureAccessResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SetupFeatureAccessResponse) GetFeatureId() string {
	if x != nil {
		return x.FeatureId
	}
	return ""
}

func (x *SetupFeatureAccessResponse) GetSubFeatureId() string {
	if x != nil {
		return x.SubFeatureId
	}
	return ""
}

func (x *SetupFeatureAccessResponse) GetScopes() *structpb.Struct {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *SetupFeatureAccessResponse) GetCreatedAtLocal() string {
	if x != nil {
		return x.CreatedAtLocal
	}
	return ""
}

func (x *SetupFeatureAccessResponse) GetCreatedAtUtc() string {
	if x != nil {
		return x.CreatedAtUtc
	}
	return ""
}

func (x *SetupFeatureAccessResponse) GetUpdatedAtLocal() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedAtLocal
	}
	return nil
}

func (x *SetupFeatureAccessResponse) GetUpdatedAtUtc() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedAtUtc
	}
	return nil
}

func (x *SetupFeatureAccessResponse) GetDemoMode() bool {
	if x != nil {
		return x.DemoMode
	}
	return false
}

func (x *SetupFeatureAccessResponse) GetIsActive() int32 {
	if x != nil {
		return x.IsActive
	}
	return 0
}

type SetupFeatureConfigResponse struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	ConfigId       string                  `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	EntityType     string                  `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId       string                  `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	OrganizationId string                  `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	SubFeatureId   string                  `protobuf:"bytes,5,opt,name=sub_feature_id,json=subFeatureId,proto3" json:"sub_feature_id,omitempty"`
	Settings       *structpb.Struct        `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	CreatedAtLocal string                  `protobuf:"bytes,7,opt,name=created_at_local,json=createdAtLocal,proto3" json:"created_at_local,omitempty"`
	CreatedAtUtc   string                  `protobuf:"bytes,8,opt,name=created_at_utc,json=createdAtUtc,proto3" json:"created_at_utc,omitempty"`
	UpdatedAtLocal *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=updated_at_local,json=updatedAtLocal,proto3" json:"updated_at_local,omitempty"`
	UpdatedAtUtc   *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=updated_at_utc,json=updatedAtUtc,proto3" json:"updated_at_utc,omitempty"`
	DemoMode       bool                    `protobuf:"varint,11,opt,name=demo_mode,json=demoMode,proto3" json:"demo_mode,omitempty"`
	IsActive       int32                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetupFeatureConfigResponse) Reset() {
	*x = SetupFeatureConfigResponse{}
	mi := &file_setup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupFeatureConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupFeatureConfigResponse) ProtoMessage() {}

func (x *SetupFeatureConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupFeatureConfigResponse.ProtoReflect.Descriptor instead.
func (*SetupFeatureConfigResponse) Descriptor() ([]byte, []int) {
	return file_setup_proto_rawDescGZIP(), []int{5}
}

func (x *SetupFeatureConfigResponse) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *SetupFeatureConfigResponse) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *SetupFeatureConfigResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *SetupFeatureConfigResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SetupFeatureConfigResponse) GetSubFeatureId() string {
	if x != nil {
		return x.SubFeatureId
	}
	return ""
}

func (x *SetupFeatureConfigResponse) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *SetupFeatureConfigResponse) GetCreatedAtLocal() string {
	if x != nil {
		return x.CreatedAtLocal
	}
	return ""
}

func (x *SetupFeatureConfigResponse) GetCreatedAtUtc() string {
	if x != nil {
		return x.CreatedAtUtc
	}
	return ""
}

func (x *SetupFeatureConfigResponse) GetUpdatedAtLocal() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedAtLocal
	}
	return nil
}

func (x *SetupFeatureConfigResponse) GetUpdatedAtUtc() *wrapperspb.StringValue {
	if x != nil {
		return x.UpdatedAtUtc
	}
	return nil
}

func (x *SetupFeatureConfigResponse) GetDemoMode() bool {
	if x != nil {
		return x.DemoMode
	}
	return false
}

func (x *SetupFeatureConfigResponse) GetIsActive() int32 {
	if x != nil {
		return x.IsActive
	}
	return 0
}

type OrganizationConfigResponse struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	Organization   *SetupOrganizationResponse    `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	Company        []*SetupCompanyResponse       `protobuf:"bytes,2,rep,name=company,proto3" json:"company,omitempty"`
	Locations      []*SetupLocationResponse      `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	FeatureAccess  []*SetupFeatureAccessResponse `protobuf:"bytes,4,rep,name=feature_access,json=featureAccess,proto3" json:"feature_access,omitempty"`
	FeatureConfigs []*SetupFeatureConfigResponse `protobuf:"bytes,5,rep,name=feature_configs,json=featureConfigs,proto3" json:"feature_configs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrganizationConfigResponse) Reset() {
	*x = OrganizationConfigResponse{}
	mi := &file_setup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationConfigResponse) ProtoMessage() {}

func (x *OrganizationConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationConfigResponse.ProtoReflect.Descriptor instead.
func (*OrganizationConfigResponse) Descriptor() ([]byte, []int) {
	return file_setup_proto_rawDescGZIP(), []int{6}
}

func (x *OrganizationConfigResponse) GetOrganization() *SetupOrganizationResponse {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *OrganizationConfigResponse) GetCompany() []*SetupCompanyResponse {
	if x != nil {
		return x.Company
	}
	return nil
}

func (x *OrganizationConfigResponse) GetLocations() []*SetupLocationResponse {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *OrganizationConfigResponse) GetFeatureAccess() []*SetupFeatureAccessResponse {
	if x != nil {
		return x.FeatureAccess
	}
	return nil
}

func (x *OrganizationConfigResponse) GetFeatureConfigs() []*SetupFeatureConfigResponse {
	if x != nil {
		return x.FeatureConfigs
	}
	return nil
}

var File_setup_proto protoreflect.FileDescriptor

const file_setup_proto_rawDesc = "" +
	"\n" +
	"\vsetup.proto\x12\n" +
	"qbsetup.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/protobuf/struct.proto\"D\n" +
	"\x19OrganizationConfigRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"\x8c\v\n" +
	"\x19SetupOrganizationResponse\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12+\n" +
	"\x11organization_name\x18\x02 \x01(\tR\x10organizationName\x12+\n" +
	"\x11organization_code\x18\x03 \x01(\tR\x10organizationCode\x12N\n" +
	"\x16organization_reference\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x15organizationReference\x12+\n" +
	"\x11organization_type\x18\x05 \x01(\tR\x10organizationType\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x06 \x01(\tR\tbrandName\x12$\n" +
	"\x0ebrand_logo_url\x18\a \x01(\tR\fbrandLogoUrl\x12\x1a\n" +
	"\bindustry\x18\b \x01(\tR\bindustry\x12H\n" +
	"\x11industry_sub_type\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\x0findustrySubType\x12B\n" +
	"\x0eorg_secret_key\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\forgSecretKey\x12@\n" +
	"\x0fcompliance_info\x18\v \x01(\v2\x17.google.protobuf.StructR\x0ecomplianceInfo\x12G\n" +
	"\x10business_segment\x18\f \x01(\v2\x1c.google.protobuf.StringValueR\x0fbusinessSegment\x12E\n" +
	"\x0fbusiness_origin\x18\r \x01(\v2\x1c.google.protobuf.StringValueR\x0ebusinessOrigin\x12\x1d\n" +
	"\n" +
	"enable_mfa\x18\x0e \x01(\bR\tenableMfa\x127\n" +
	"\bmfa_type\x18\x0f \x01(\v2\x1c.google.protobuf.StringValueR\amfaType\x12>\n" +
	"\fmfa_sub_type\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"mfaSubType\x12;\n" +
	"\n" +
	"start_date\x18\x11 \x01(\v2\x1c.google.protobuf.StringValueR\tstartDate\x127\n" +
	"\bend_date\x18\x12 \x01(\v2\x1c.google.protobuf.StringValueR\aendDate\x12P\n" +
	"\x15date_of_incorporation\x18\x13 \x01(\v2\x1c.google.protobuf.StringValueR\x13dateOfIncorporation\x128\n" +
	"\btimezone\x18\x14 \x01(\v2\x1c.google.protobuf.StringValueR\btimezone\x12(\n" +
	"\x10created_at_local\x18\x15 \x01(\tR\x0ecreatedAtLocal\x12$\n" +
	"\x0ecreated_at_utc\x18\x16 \x01(\tR\fcreatedAtUtc\x12F\n" +
	"\x10updated_at_local\x18\x17 \x01(\v2\x1c.google.protobuf.StringValueR\x0eupdatedAtLocal\x12B\n" +
	"\x0eupdated_at_utc\x18\x18 \x01(\v2\x1c.google.protobuf.StringValueR\fupdatedAtUtc\x12\x1b\n" +
	"\tdemo_mode\x18\x19 \x01(\bR\bdemoMode\x12\x1b\n" +
	"\tis_active\x18\x1a \x01(\x05R\bisActive\"\x85\b\n" +
	"\x14SetupCompanyResponse\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fcompany_name\x18\x03 \x01(\tR\vcompanyName\x12D\n" +
	"\x11company_reference\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x10companyReference\x12!\n" +
	"\fcompany_type\x18\x05 \x01(\tR\vcompanyType\x12;\n" +
	"\n" +
	"brand_name\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\tbrandName\x128\n" +
	"\bindustry\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\bindustry\x12H\n" +
	"\x11industry_sub_type\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x0findustrySubType\x12@\n" +
	"\x0fcompliance_info\x18\t \x01(\v2\x17.google.protobuf.StructR\x0ecomplianceInfo\x12;\n" +
	"\n" +
	"start_date\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\tstartDate\x127\n" +
	"\bend_date\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\aendDate\x12P\n" +
	"\x15date_of_incorporation\x18\f \x01(\v2\x1c.google.protobuf.StringValueR\x13dateOfIncorporation\x128\n" +
	"\btimezone\x18\r \x01(\v2\x1c.google.protobuf.StringValueR\btimezone\x12(\n" +
	"\x10created_at_local\x18\x0e \x01(\tR\x0ecreatedAtLocal\x12$\n" +
	"\x0ecreated_at_utc\x18\x0f \x01(\tR\fcreatedAtUtc\x12F\n" +
	"\x10updated_at_local\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueR\x0eupdatedAtLocal\x12B\n" +
	"\x0eupdated_at_utc\x18\x11 \x01(\v2\x1c.google.protobuf.StringValueR\fupdatedAtUtc\x12\x1b\n" +
	"\tdemo_mode\x18\x12 \x01(\bR\bdemoMode\x12\x1b\n" +
	"\tis_active\x18\x13 \x01(\x05R\bisActive\"\x9e\a\n" +
	"\x15SetupLocationResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\x12#\n" +
	"\rlocation_name\x18\x04 \x01(\tR\flocationName\x12F\n" +
	"\x12location_reference\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x11locationReference\x12#\n" +
	"\rlocation_type\x18\x06 \x01(\tR\flocationType\x128\n" +
	"\bindustry\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\bindustry\x12H\n" +
	"\x11industry_sub_type\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x0findustrySubType\x12@\n" +
	"\x0fcompliance_info\x18\t \x01(\v2\x17.google.protobuf.StructR\x0ecomplianceInfo\x12;\n" +
	"\n" +
	"start_date\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\tstartDate\x127\n" +
	"\bend_date\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\aendDate\x128\n" +
	"\btimezone\x18\f \x01(\v2\x1c.google.protobuf.StringValueR\btimezone\x12(\n" +
	"\x10created_at_local\x18\r \x01(\tR\x0ecreatedAtLocal\x12$\n" +
	"\x0ecreated_at_utc\x18\x0e \x01(\tR\fcreatedAtUtc\x12F\n" +
	"\x10updated_at_local\x18\x0f \x01(\v2\x1c.google.protobuf.StringValueR\x0eupdatedAtLocal\x12B\n" +
	"\x0eupdated_at_utc\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueR\fupdatedAtUtc\x12\x1b\n" +
	"\tdemo_mode\x18\x11 \x01(\bR\bdemoMode\x12\x1b\n" +
	"\tis_active\x18\x12 \x01(\x05R\bisActive\"\xee\x03\n" +
	"\x1aSetupFeatureAccessResponse\x12\x1b\n" +
	"\taccess_id\x18\x01 \x01(\tR\baccessId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x03 \x01(\tR\tfeatureId\x12$\n" +
	"\x0esub_feature_id\x18\x04 \x01(\tR\fsubFeatureId\x12/\n" +
	"\x06scopes\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06scopes\x12(\n" +
	"\x10created_at_local\x18\x06 \x01(\tR\x0ecreatedAtLocal\x12$\n" +
	"\x0ecreated_at_utc\x18\a \x01(\tR\fcreatedAtUtc\x12F\n" +
	"\x10updated_at_local\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x0eupdatedAtLocal\x12B\n" +
	"\x0eupdated_at_utc\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\fupdatedAtUtc\x12\x1b\n" +
	"\tdemo_mode\x18\n" +
	" \x01(\bR\bdemoMode\x12\x1b\n" +
	"\tis_active\x18\v \x01(\x05R\bisActive\"\x91\x04\n" +
	"\x1aSetupFeatureConfigResponse\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\x12$\n" +
	"\x0esub_feature_id\x18\x05 \x01(\tR\fsubFeatureId\x123\n" +
	"\bsettings\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bsettings\x12(\n" +
	"\x10created_at_local\x18\a \x01(\tR\x0ecreatedAtLocal\x12$\n" +
	"\x0ecreated_at_utc\x18\b \x01(\tR\fcreatedAtUtc\x12F\n" +
	"\x10updated_at_local\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\x0eupdatedAtLocal\x12B\n" +
	"\x0eupdated_at_utc\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\fupdatedAtUtc\x12\x1b\n" +
	"\tdemo_mode\x18\v \x01(\bR\bdemoMode\x12\x1b\n" +
	"\tis_active\x18\f \x01(\x05R\bisActive\"\x84\x03\n" +
	"\x1aOrganizationConfigResponse\x12I\n" +
	"\forganization\x18\x01 \x01(\v2%.qbsetup.v1.SetupOrganizationResponseR\forganization\x12:\n" +
	"\acompany\x18\x02 \x03(\v2 .qbsetup.v1.SetupCompanyResponseR\acompany\x12?\n" +
	"\tlocations\x18\x03 \x03(\v2!.qbsetup.v1.SetupLocationResponseR\tlocations\x12M\n" +
	"\x0efeature_access\x18\x04 \x03(\v2&.qbsetup.v1.SetupFeatureAccessResponseR\rfeatureAccess\x12O\n" +
	"\x0ffeature_configs\x18\x05 \x03(\v2&.qbsetup.v1.SetupFeatureConfigResponseR\x0efeatureConfigs2s\n" +
	"\fSetupService\x12c\n" +
	"\x12OrganizationConfig\x12%.qbsetup.v1.OrganizationConfigRequest\x1a&.qbsetup.v1.OrganizationConfigResponseB$Z\"qb-accounting/internal/proto/setupb\x06proto3"

var (
	file_setup_proto_rawDescOnce sync.Once
	file_setup_proto_rawDescData []byte
)

func file_setup_proto_rawDescGZIP() []byte {
	file_setup_proto_rawDescOnce.Do(func() {
		file_setup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_setup_proto_rawDesc), len(file_setup_proto_rawDesc)))
	})
	return file_setup_proto_rawDescData
}

var file_setup_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_setup_proto_goTypes = []any{
	(*OrganizationConfigRequest)(nil),  // 0: qbsetup.v1.OrganizationConfigRequest
	(*SetupOrganizationResponse)(nil),  // 1: qbsetup.v1.SetupOrganizationResponse
	(*SetupCompanyResponse)(nil),       // 2: qbsetup.v1.SetupCompanyResponse
	(*SetupLocationResponse)(nil),      // 3: qbsetup.v1.SetupLocationResponse
	(*SetupFeatureAccessResponse)(nil), // 4: qbsetup.v1.SetupFeatureAccessResponse
	(*SetupFeatureConfigResponse)(nil), // 5: qbsetup.v1.SetupFeatureConfigResponse
	(*OrganizationConfigResponse)(nil), // 6: qbsetup.v1.OrganizationConfigResponse
	(*structpb.Struct)(nil),            // 7: google.protobuf.Struct
	(*wrapperspb.StringValue)(nil),     // 8: google.protobuf.StringValue
}
var file_setup_proto_depIdxs = []int32{
	7,  // 0: qbsetup.v1.SetupOrganizationResponse.organization_reference:type_name -> google.protobuf.Struct
	8,  // 1: qbsetup.v1.SetupOrganizationResponse.industry_sub_type:type_name -> google.protobuf.StringValue
	8,  // 2: qbsetup.v1.SetupOrganizationResponse.org_secret_key:type_name -> google.protobuf.StringValue
	7,  // 3: qbsetup.v1.SetupOrganizationResponse.compliance_info:type_name -> google.protobuf.Struct
	8,  // 4: qbsetup.v1.SetupOrganizationResponse.business_segment:type_name -> google.protobuf.StringValue
	8,  // 5: qbsetup.v1.SetupOrganizationResponse.business_origin:type_name -> google.protobuf.StringValue
	8,  // 6: qbsetup.v1.SetupOrganizationResponse.mfa_type:type_name -> google.protobuf.StringValue
	8,  // 7: qbsetup.v1.SetupOrganizationResponse.mfa_sub_type:type_name -> google.protobuf.StringValue
	8,  // 8: qbsetup.v1.SetupOrganizationResponse.start_date:type_name -> google.protobuf.StringValue
	8,  // 9: qbsetup.v1.SetupOrganizationResponse.end_date:type_name -> google.protobuf.StringValue
	8,  // 10: qbsetup.v1.SetupOrganizationResponse.date_of_incorporation:type_name -> google.protobuf.StringValue
	8,  // 11: qbsetup.v1.SetupOrganizationResponse.timezone:type_name -> google.protobuf.StringValue
	8,  // 12: qbsetup.v1.SetupOrganizationResponse.updated_at_local:type_name -> google.protobuf.StringValue
	8,  // 13: qbsetup.v1.SetupOrganizationResponse.updated_at_utc:type_name -> google.protobuf.StringValue
	7,  // 14: qbsetup.v1.SetupCompanyResponse.company_reference:type_name -> google.protobuf.Struct
	8,  // 15: qbsetup.v1.SetupCompanyResponse.brand_name:type_name -> google.protobuf.StringValue
	8,  // 16: qbsetup.v1.SetupCompanyResponse.industry:type_name -> google.protobuf.StringValue
	8,  // 17: qbsetup.v1.SetupCompanyResponse.industry_sub_type:type_name -> google.protobuf.StringValue
	7,  // 18: qbsetup.v1.SetupCompanyResponse.compliance_info:type_name -> google.protobuf.Struct
	8,  // 19: qbsetup.v1.SetupCompanyResponse.start_date:type_name -> google.protobuf.StringValue
	8,  // 20: qbsetup.v1.SetupCompanyResponse.end_date:type_name -> google.protobuf.StringValue
	8,  // 21: qbsetup.v1.SetupCompanyResponse.date_of_incorporation:type_name -> google.protobuf.StringValue
	8,  // 22: qbsetup.v1.SetupCompanyResponse.timezone:type_name -> google.protobuf.StringValue
	8,  // 23: qbsetup.v1.SetupCompanyResponse.updated_at_local:type_name -> google.protobuf.StringValue
	8,  // 24: qbsetup.v1.SetupCompanyResponse.updated_at_utc:type_name -> google.protobuf.StringValue
	7,  // 25: qbsetup.v1.SetupLocationResponse.location_reference:type_name -> google.protobuf.Struct
	8,  // 26: qbsetup.v1.SetupLocationResponse.industry:type_name -> google.protobuf.StringValue
	8,  // 27: qbsetup.v1.SetupLocationResponse.industry_sub_type:type_name -> google.protobuf.StringValue
	7,  // 28: qbsetup.v1.SetupLocationResponse.compliance_info:type_name -> google.protobuf.Struct
	8,  // 29: qbsetup.v1.SetupLocationResponse.start_date:type_name -> google.protobuf.StringValue
	8,  // 30: qbsetup.v1.SetupLocationResponse.end_date:type_name -> google.protobuf.StringValue
	8,  // 31: qbsetup.v1.SetupLocationResponse.timezone:type_name -> google.protobuf.StringValue
	8,  // 32: qbsetup.v1.SetupLocationResponse.updated_at_local:type_name -> google.protobuf.StringValue
	8,  // 33: qbsetup.v1.SetupLocationResponse.updated_at_utc:type_name -> google.protobuf.StringValue
	7,  // 34: qbsetup.v1.SetupFeatureAccessResponse.scopes:type_name -> google.protobuf.Struct
	8,  // 35: qbsetup.v1.SetupFeatureAccessResponse.updated_at_local:type_name -> google.protobuf.StringValue
	8,  // 36: qbsetup.v1.SetupFeatureAccessResponse.updated_at_utc:type_name -> google.protobuf.StringValue
	7,  // 37: qbsetup.v1.SetupFeatureConfigResponse.settings:type_name -> google.protobuf.Struct
	8,  // 38: qbsetup.v1.SetupFeatureConfigResponse.updated_at_local:type_name -> google.protobuf.StringValue
	8,  // 39: qbsetup.v1.SetupFeatureConfigResponse.updated_at_utc:type_name -> google.protobuf.StringValue
	1,  // 40: qbsetup.v1.OrganizationConfigResponse.organization:type_name -> qbsetup.v1.SetupOrganizationResponse
	2,  // 41: qbsetup.v1.OrganizationConfigResponse.company:type_name -> qbsetup.v1.SetupCompanyResponse
	3,  // 42: qbsetup.v1.OrganizationConfigResponse.locations:type_name -> qbsetup.v1.SetupLocationResponse
	4,  // 43: qbsetup.v1.OrganizationConfigResponse.feature_access:type_name -> qbsetup.v1.SetupFeatureAccessResponse
	5,  // 44: qbsetup.v1.OrganizationConfigResponse.feature_configs:type_name -> qbsetup.v1.SetupFeatureConfigResponse
	0,  // 45: qbsetup.v1.SetupService.OrganizationConfig:input_type -> qbsetup.v1.OrganizationConfigRequest
	6,  // 46: qbsetup.v1.SetupService.OrganizationConfig:output_type -> qbsetup.v1.OrganizationConfigResponse
	46, // [46:47] is the sub-list for method output_type
	45, // [45:46] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_setup_proto_init() }
func file_setup_proto_init() {
	if File_setup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_setup_proto_rawDesc), len(file_setup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_setup_proto_goTypes,
		DependencyIndexes: file_setup_proto_depIdxs,
		MessageInfos:      file_setup_proto_msgTypes,
	}.Build()
	File_setup_proto = out.File
	file_setup_proto_goTypes = nil
	file_setup_proto_depIdxs = nil
}
