// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: product.proto

package catalogue

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductService_GetProductsByIDs_FullMethodName      = "/catalogue.ProductService/GetProductsByIDs"
	ProductService_GetProductGroupsByIDs_FullMethodName = "/catalogue.ProductService/GetProductGroupsByIDs"
	ProductService_GetMeasurementUnits_FullMethodName   = "/catalogue.ProductService/GetMeasurementUnits"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProductService provides gRPC methods for product operations
type ProductServiceClient interface {
	// GetProductsByIDs fetches products by their IDs
	GetProductsByIDs(ctx context.Context, in *GetProductsByIDsRequest, opts ...grpc.CallOption) (*GetProductsByIDsResponse, error)
	// GetProductGroupsByIDs fetches product groups (lots/batches) by their IDs
	GetProductGroupsByIDs(ctx context.Context, in *GetProductGroupsByIDsRequest, opts ...grpc.CallOption) (*GetProductGroupsByIDsResponse, error)
	// GetMeasurementUnits fetches measurement units for an organization
	GetMeasurementUnits(ctx context.Context, in *GetMeasurementUnitsRequest, opts ...grpc.CallOption) (*GetMeasurementUnitsResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProductsByIDs(ctx context.Context, in *GetProductsByIDsRequest, opts ...grpc.CallOption) (*GetProductsByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductsByIDsResponse)
	err := c.cc.Invoke(ctx, ProductService_GetProductsByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductGroupsByIDs(ctx context.Context, in *GetProductGroupsByIDsRequest, opts ...grpc.CallOption) (*GetProductGroupsByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductGroupsByIDsResponse)
	err := c.cc.Invoke(ctx, ProductService_GetProductGroupsByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetMeasurementUnits(ctx context.Context, in *GetMeasurementUnitsRequest, opts ...grpc.CallOption) (*GetMeasurementUnitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeasurementUnitsResponse)
	err := c.cc.Invoke(ctx, ProductService_GetMeasurementUnits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility.
//
// ProductService provides gRPC methods for product operations
type ProductServiceServer interface {
	// GetProductsByIDs fetches products by their IDs
	GetProductsByIDs(context.Context, *GetProductsByIDsRequest) (*GetProductsByIDsResponse, error)
	// GetProductGroupsByIDs fetches product groups (lots/batches) by their IDs
	GetProductGroupsByIDs(context.Context, *GetProductGroupsByIDsRequest) (*GetProductGroupsByIDsResponse, error)
	// GetMeasurementUnits fetches measurement units for an organization
	GetMeasurementUnits(context.Context, *GetMeasurementUnitsRequest) (*GetMeasurementUnitsResponse, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) GetProductsByIDs(context.Context, *GetProductsByIDsRequest) (*GetProductsByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductsByIDs not implemented")
}
func (UnimplementedProductServiceServer) GetProductGroupsByIDs(context.Context, *GetProductGroupsByIDsRequest) (*GetProductGroupsByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductGroupsByIDs not implemented")
}
func (UnimplementedProductServiceServer) GetMeasurementUnits(context.Context, *GetMeasurementUnitsRequest) (*GetMeasurementUnitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMeasurementUnits not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}
func (UnimplementedProductServiceServer) testEmbeddedByValue()                        {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	// If the following call panics, it indicates UnimplementedProductServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_GetProductsByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductsByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetProductsByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductsByIDs(ctx, req.(*GetProductsByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductGroupsByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductGroupsByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductGroupsByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetProductGroupsByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductGroupsByIDs(ctx, req.(*GetProductGroupsByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetMeasurementUnits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeasurementUnitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetMeasurementUnits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_GetMeasurementUnits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetMeasurementUnits(ctx, req.(*GetMeasurementUnitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalogue.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductsByIDs",
			Handler:    _ProductService_GetProductsByIDs_Handler,
		},
		{
			MethodName: "GetProductGroupsByIDs",
			Handler:    _ProductService_GetProductGroupsByIDs_Handler,
		},
		{
			MethodName: "GetMeasurementUnits",
			Handler:    _ProductService_GetMeasurementUnits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
