// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/catalogue/product.proto

package catalogue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetProductsByIDsRequest is the request for fetching multiple products
type GetProductsByIDsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProductIds     []string               `protobuf:"bytes,2,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProductsByIDsRequest) Reset() {
	*x = GetProductsByIDsRequest{}
	mi := &file_proto_catalogue_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIDsRequest) ProtoMessage() {}

func (x *GetProductsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalogue_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalogue_product_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductsByIDsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetProductsByIDsRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

// GetProductsByIDsResponse is the response containing products
type GetProductsByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIDsResponse) Reset() {
	*x = GetProductsByIDsResponse{}
	mi := &file_proto_catalogue_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIDsResponse) ProtoMessage() {}

func (x *GetProductsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalogue_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalogue_product_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductsByIDsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

// Product represents a product/item from the catalogue
type Product struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemId         string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Basic Information
	ProductName       string   `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductType       string   `protobuf:"bytes,4,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"` // PRODUCT, SERVICE, BUNDLE, MODIFIER, GIFT_VOUCHER, MEMBERSHIP
	ShortDescription  *string  `protobuf:"bytes,5,opt,name=short_description,json=shortDescription,proto3,oneof" json:"short_description,omitempty"`
	LongDescription   *string  `protobuf:"bytes,6,opt,name=long_description,json=longDescription,proto3,oneof" json:"long_description,omitempty"`
	Images            []string `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	ColourCode        *string  `protobuf:"bytes,8,opt,name=colour_code,json=colourCode,proto3,oneof" json:"colour_code,omitempty"`
	MeasurementUnitId *string  `protobuf:"bytes,9,opt,name=measurement_unit_id,json=measurementUnitId,proto3,oneof" json:"measurement_unit_id,omitempty"`
	OperationalUnitId *string  `protobuf:"bytes,10,opt,name=operational_unit_id,json=operationalUnitId,proto3,oneof" json:"operational_unit_id,omitempty"`
	// Classification (as JSON string)
	Classification *string `protobuf:"bytes,11,opt,name=classification,proto3,oneof" json:"classification,omitempty"`
	// Pricing
	IsSellableOnPos      bool    `protobuf:"varint,12,opt,name=is_sellable_on_pos,json=isSellableOnPos,proto3" json:"is_sellable_on_pos,omitempty"`
	AllowVariablePricing bool    `protobuf:"varint,13,opt,name=allow_variable_pricing,json=allowVariablePricing,proto3" json:"allow_variable_pricing,omitempty"`
	PriceIncludesTaxes   bool    `protobuf:"varint,14,opt,name=price_includes_taxes,json=priceIncludesTaxes,proto3" json:"price_includes_taxes,omitempty"`
	DefaultSellingPrice  float64 `protobuf:"fixed64,15,opt,name=default_selling_price,json=defaultSellingPrice,proto3" json:"default_selling_price,omitempty"`
	EnableProductGroup   bool    `protobuf:"varint,16,opt,name=enable_product_group,json=enableProductGroup,proto3" json:"enable_product_group,omitempty"`
	PricingAttribute     *string `protobuf:"bytes,17,opt,name=pricing_attribute,json=pricingAttribute,proto3,oneof" json:"pricing_attribute,omitempty"` // JSON string
	// Inventory
	IsInventoryManaged       bool    `protobuf:"varint,18,opt,name=is_inventory_managed,json=isInventoryManaged,proto3" json:"is_inventory_managed,omitempty"`
	Barcode                  *string `protobuf:"bytes,19,opt,name=barcode,proto3,oneof" json:"barcode,omitempty"`
	Sku                      *string `protobuf:"bytes,20,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	DimensionUnit            *string `protobuf:"bytes,21,opt,name=dimension_unit,json=dimensionUnit,proto3,oneof" json:"dimension_unit,omitempty"`
	PackagingInfo            *string `protobuf:"bytes,22,opt,name=packaging_info,json=packagingInfo,proto3,oneof" json:"packaging_info,omitempty"`                                    // JSON string
	InventoryReductionMethod *string `protobuf:"bytes,23,opt,name=inventory_reduction_method,json=inventoryReductionMethod,proto3,oneof" json:"inventory_reduction_method,omitempty"` // DIRECT, INDIRECT
	RecipeId                 *string `protobuf:"bytes,24,opt,name=recipe_id,json=recipeId,proto3,oneof" json:"recipe_id,omitempty"`
	DefaultStockAlertLevel   *int32  `protobuf:"varint,25,opt,name=default_stock_alert_level,json=defaultStockAlertLevel,proto3,oneof" json:"default_stock_alert_level,omitempty"`
	DefaultSafeStockLevel    *int32  `protobuf:"varint,26,opt,name=default_safe_stock_level,json=defaultSafeStockLevel,proto3,oneof" json:"default_safe_stock_level,omitempty"`
	// Billing & Compliance
	CountryOfOrigin           *string `protobuf:"bytes,27,opt,name=country_of_origin,json=countryOfOrigin,proto3,oneof" json:"country_of_origin,omitempty"`
	HsnSacCode                *string `protobuf:"bytes,28,opt,name=hsn_sac_code,json=hsnSacCode,proto3,oneof" json:"hsn_sac_code,omitempty"`
	DisableSalesOnNoStock     bool    `protobuf:"varint,29,opt,name=disable_sales_on_no_stock,json=disableSalesOnNoStock,proto3" json:"disable_sales_on_no_stock,omitempty"`
	DisableSalesOnStockExpiry bool    `protobuf:"varint,30,opt,name=disable_sales_on_stock_expiry,json=disableSalesOnStockExpiry,proto3" json:"disable_sales_on_stock_expiry,omitempty"`
	ReturnExchange            *string `protobuf:"bytes,31,opt,name=return_exchange,json=returnExchange,proto3,oneof" json:"return_exchange,omitempty"` // JSON string
	// Attributes
	Attributes         *string `protobuf:"bytes,32,opt,name=attributes,proto3,oneof" json:"attributes,omitempty"`                                             // JSON string
	Relationships      *string `protobuf:"bytes,33,opt,name=relationships,proto3,oneof" json:"relationships,omitempty"`                                       // JSON string
	ItemTypeAttributes *string `protobuf:"bytes,34,opt,name=item_type_attributes,json=itemTypeAttributes,proto3,oneof" json:"item_type_attributes,omitempty"` // JSON string
	// Audit fields
	CreatedBy      *string `protobuf:"bytes,35,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	UpdatedBy      *string `protobuf:"bytes,36,opt,name=updated_by,json=updatedBy,proto3,oneof" json:"updated_by,omitempty"`
	CreatedAtLocal string  `protobuf:"bytes,37,opt,name=created_at_local,json=createdAtLocal,proto3" json:"created_at_local,omitempty"`
	CreatedAtUtc   string  `protobuf:"bytes,38,opt,name=created_at_utc,json=createdAtUtc,proto3" json:"created_at_utc,omitempty"`
	UpdatedAtLocal *string `protobuf:"bytes,39,opt,name=updated_at_local,json=updatedAtLocal,proto3,oneof" json:"updated_at_local,omitempty"`
	UpdatedAtUtc   *string `protobuf:"bytes,40,opt,name=updated_at_utc,json=updatedAtUtc,proto3,oneof" json:"updated_at_utc,omitempty"`
	// System fields
	DemoMode      bool  `protobuf:"varint,41,opt,name=demo_mode,json=demoMode,proto3" json:"demo_mode,omitempty"`
	IsActive      int32 `protobuf:"varint,42,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_catalogue_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalogue_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_catalogue_product_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Product) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Product) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Product) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *Product) GetShortDescription() string {
	if x != nil && x.ShortDescription != nil {
		return *x.ShortDescription
	}
	return ""
}

func (x *Product) GetLongDescription() string {
	if x != nil && x.LongDescription != nil {
		return *x.LongDescription
	}
	return ""
}

func (x *Product) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Product) GetColourCode() string {
	if x != nil && x.ColourCode != nil {
		return *x.ColourCode
	}
	return ""
}

func (x *Product) GetMeasurementUnitId() string {
	if x != nil && x.MeasurementUnitId != nil {
		return *x.MeasurementUnitId
	}
	return ""
}

func (x *Product) GetOperationalUnitId() string {
	if x != nil && x.OperationalUnitId != nil {
		return *x.OperationalUnitId
	}
	return ""
}

func (x *Product) GetClassification() string {
	if x != nil && x.Classification != nil {
		return *x.Classification
	}
	return ""
}

func (x *Product) GetIsSellableOnPos() bool {
	if x != nil {
		return x.IsSellableOnPos
	}
	return false
}

func (x *Product) GetAllowVariablePricing() bool {
	if x != nil {
		return x.AllowVariablePricing
	}
	return false
}

func (x *Product) GetPriceIncludesTaxes() bool {
	if x != nil {
		return x.PriceIncludesTaxes
	}
	return false
}

func (x *Product) GetDefaultSellingPrice() float64 {
	if x != nil {
		return x.DefaultSellingPrice
	}
	return 0
}

func (x *Product) GetEnableProductGroup() bool {
	if x != nil {
		return x.EnableProductGroup
	}
	return false
}

func (x *Product) GetPricingAttribute() string {
	if x != nil && x.PricingAttribute != nil {
		return *x.PricingAttribute
	}
	return ""
}

func (x *Product) GetIsInventoryManaged() bool {
	if x != nil {
		return x.IsInventoryManaged
	}
	return false
}

func (x *Product) GetBarcode() string {
	if x != nil && x.Barcode != nil {
		return *x.Barcode
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

func (x *Product) GetDimensionUnit() string {
	if x != nil && x.DimensionUnit != nil {
		return *x.DimensionUnit
	}
	return ""
}

func (x *Product) GetPackagingInfo() string {
	if x != nil && x.PackagingInfo != nil {
		return *x.PackagingInfo
	}
	return ""
}

func (x *Product) GetInventoryReductionMethod() string {
	if x != nil && x.InventoryReductionMethod != nil {
		return *x.InventoryReductionMethod
	}
	return ""
}

func (x *Product) GetRecipeId() string {
	if x != nil && x.RecipeId != nil {
		return *x.RecipeId
	}
	return ""
}

func (x *Product) GetDefaultStockAlertLevel() int32 {
	if x != nil && x.DefaultStockAlertLevel != nil {
		return *x.DefaultStockAlertLevel
	}
	return 0
}

func (x *Product) GetDefaultSafeStockLevel() int32 {
	if x != nil && x.DefaultSafeStockLevel != nil {
		return *x.DefaultSafeStockLevel
	}
	return 0
}

func (x *Product) GetCountryOfOrigin() string {
	if x != nil && x.CountryOfOrigin != nil {
		return *x.CountryOfOrigin
	}
	return ""
}

func (x *Product) GetHsnSacCode() string {
	if x != nil && x.HsnSacCode != nil {
		return *x.HsnSacCode
	}
	return ""
}

func (x *Product) GetDisableSalesOnNoStock() bool {
	if x != nil {
		return x.DisableSalesOnNoStock
	}
	return false
}

func (x *Product) GetDisableSalesOnStockExpiry() bool {
	if x != nil {
		return x.DisableSalesOnStockExpiry
	}
	return false
}

func (x *Product) GetReturnExchange() string {
	if x != nil && x.ReturnExchange != nil {
		return *x.ReturnExchange
	}
	return ""
}

func (x *Product) GetAttributes() string {
	if x != nil && x.Attributes != nil {
		return *x.Attributes
	}
	return ""
}

func (x *Product) GetRelationships() string {
	if x != nil && x.Relationships != nil {
		return *x.Relationships
	}
	return ""
}

func (x *Product) GetItemTypeAttributes() string {
	if x != nil && x.ItemTypeAttributes != nil {
		return *x.ItemTypeAttributes
	}
	return ""
}

func (x *Product) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *Product) GetUpdatedBy() string {
	if x != nil && x.UpdatedBy != nil {
		return *x.UpdatedBy
	}
	return ""
}

func (x *Product) GetCreatedAtLocal() string {
	if x != nil {
		return x.CreatedAtLocal
	}
	return ""
}

func (x *Product) GetCreatedAtUtc() string {
	if x != nil {
		return x.CreatedAtUtc
	}
	return ""
}

func (x *Product) GetUpdatedAtLocal() string {
	if x != nil && x.UpdatedAtLocal != nil {
		return *x.UpdatedAtLocal
	}
	return ""
}

func (x *Product) GetUpdatedAtUtc() string {
	if x != nil && x.UpdatedAtUtc != nil {
		return *x.UpdatedAtUtc
	}
	return ""
}

func (x *Product) GetDemoMode() bool {
	if x != nil {
		return x.DemoMode
	}
	return false
}

func (x *Product) GetIsActive() int32 {
	if x != nil {
		return x.IsActive
	}
	return 0
}

type GetProductGroupsByIDsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId  string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProductGroupIds []string               `protobuf:"bytes,2,rep,name=product_group_ids,json=productGroupIds,proto3" json:"product_group_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetProductGroupsByIDsRequest) Reset() {
	*x = GetProductGroupsByIDsRequest{}
	mi := &file_proto_catalogue_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductGroupsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductGroupsByIDsRequest) ProtoMessage() {}

func (x *GetProductGroupsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalogue_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductGroupsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetProductGroupsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalogue_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductGroupsByIDsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetProductGroupsByIDsRequest) GetProductGroupIds() []string {
	if x != nil {
		return x.ProductGroupIds
	}
	return nil
}

type GetProductGroupsByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductGroups []*ProductGroup        `protobuf:"bytes,1,rep,name=product_groups,json=productGroups,proto3" json:"product_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductGroupsByIDsResponse) Reset() {
	*x = GetProductGroupsByIDsResponse{}
	mi := &file_proto_catalogue_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductGroupsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductGroupsByIDsResponse) ProtoMessage() {}

func (x *GetProductGroupsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalogue_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductGroupsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetProductGroupsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalogue_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductGroupsByIDsResponse) GetProductGroups() []*ProductGroup {
	if x != nil {
		return x.ProductGroups
	}
	return nil
}

type ProductGroup struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ProductGroupId           string                 `protobuf:"bytes,1,opt,name=product_group_id,json=productGroupId,proto3" json:"product_group_id,omitempty"`
	OrganizationId           string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ProductGroupName         string                 `protobuf:"bytes,3,opt,name=product_group_name,json=productGroupName,proto3" json:"product_group_name,omitempty"`
	ProductId                string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ShortDescription         *string                `protobuf:"bytes,5,opt,name=short_description,json=shortDescription,proto3,oneof" json:"short_description,omitempty"`
	LongDescription          *string                `protobuf:"bytes,6,opt,name=long_description,json=longDescription,proto3,oneof" json:"long_description,omitempty"`
	PgStatus                 string                 `protobuf:"bytes,7,opt,name=pg_status,json=pgStatus,proto3" json:"pg_status,omitempty"`
	Images                   []string               `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	PgBarcode                *string                `protobuf:"bytes,9,opt,name=pg_barcode,json=pgBarcode,proto3,oneof" json:"pg_barcode,omitempty"`
	PgSku                    *string                `protobuf:"bytes,10,opt,name=pg_sku,json=pgSku,proto3,oneof" json:"pg_sku,omitempty"`
	ManufacturingDate        *string                `protobuf:"bytes,11,opt,name=manufacturing_date,json=manufacturingDate,proto3,oneof" json:"manufacturing_date,omitempty"`
	ExpiryDate               *string                `protobuf:"bytes,12,opt,name=expiry_date,json=expiryDate,proto3,oneof" json:"expiry_date,omitempty"`
	ShelfLife                *int32                 `protobuf:"varint,13,opt,name=shelf_life,json=shelfLife,proto3,oneof" json:"shelf_life,omitempty"`
	CostPerUnit              *float64               `protobuf:"fixed64,14,opt,name=cost_per_unit,json=costPerUnit,proto3,oneof" json:"cost_per_unit,omitempty"`
	FulfillmentConfiguration *string                `protobuf:"bytes,15,opt,name=fulfillment_configuration,json=fulfillmentConfiguration,proto3,oneof" json:"fulfillment_configuration,omitempty"`
	Attributes               *string                `protobuf:"bytes,16,opt,name=attributes,proto3,oneof" json:"attributes,omitempty"`
	SellByDate               *string                `protobuf:"bytes,17,opt,name=sell_by_date,json=sellByDate,proto3,oneof" json:"sell_by_date,omitempty"`
	Mrp                      *float64               `protobuf:"fixed64,18,opt,name=mrp,proto3,oneof" json:"mrp,omitempty"`
	ReturnConfiguration      *string                `protobuf:"bytes,19,opt,name=return_configuration,json=returnConfiguration,proto3,oneof" json:"return_configuration,omitempty"`
	ExchangeConfiguration    *string                `protobuf:"bytes,20,opt,name=exchange_configuration,json=exchangeConfiguration,proto3,oneof" json:"exchange_configuration,omitempty"`
	CreatedAt                *string                `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	UpdatedAt                *string                `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ProductGroup) Reset() {
	*x = ProductGroup{}
	mi := &file_proto_catalogue_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductGroup) ProtoMessage() {}

func (x *ProductGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalogue_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductGroup.ProtoReflect.Descriptor instead.
func (*ProductGroup) Descriptor() ([]byte, []int) {
	return file_proto_catalogue_product_proto_rawDescGZIP(), []int{5}
}

func (x *ProductGroup) GetProductGroupId() string {
	if x != nil {
		return x.ProductGroupId
	}
	return ""
}

func (x *ProductGroup) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ProductGroup) GetProductGroupName() string {
	if x != nil {
		return x.ProductGroupName
	}
	return ""
}

func (x *ProductGroup) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductGroup) GetShortDescription() string {
	if x != nil && x.ShortDescription != nil {
		return *x.ShortDescription
	}
	return ""
}

func (x *ProductGroup) GetLongDescription() string {
	if x != nil && x.LongDescription != nil {
		return *x.LongDescription
	}
	return ""
}

func (x *ProductGroup) GetPgStatus() string {
	if x != nil {
		return x.PgStatus
	}
	return ""
}

func (x *ProductGroup) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductGroup) GetPgBarcode() string {
	if x != nil && x.PgBarcode != nil {
		return *x.PgBarcode
	}
	return ""
}

func (x *ProductGroup) GetPgSku() string {
	if x != nil && x.PgSku != nil {
		return *x.PgSku
	}
	return ""
}

func (x *ProductGroup) GetManufacturingDate() string {
	if x != nil && x.ManufacturingDate != nil {
		return *x.ManufacturingDate
	}
	return ""
}

func (x *ProductGroup) GetExpiryDate() string {
	if x != nil && x.ExpiryDate != nil {
		return *x.ExpiryDate
	}
	return ""
}

func (x *ProductGroup) GetShelfLife() int32 {
	if x != nil && x.ShelfLife != nil {
		return *x.ShelfLife
	}
	return 0
}

func (x *ProductGroup) GetCostPerUnit() float64 {
	if x != nil && x.CostPerUnit != nil {
		return *x.CostPerUnit
	}
	return 0
}

func (x *ProductGroup) GetFulfillmentConfiguration() string {
	if x != nil && x.FulfillmentConfiguration != nil {
		return *x.FulfillmentConfiguration
	}
	return ""
}

func (x *ProductGroup) GetAttributes() string {
	if x != nil && x.Attributes != nil {
		return *x.Attributes
	}
	return ""
}

func (x *ProductGroup) GetSellByDate() string {
	if x != nil && x.SellByDate != nil {
		return *x.SellByDate
	}
	return ""
}

func (x *ProductGroup) GetMrp() float64 {
	if x != nil && x.Mrp != nil {
		return *x.Mrp
	}
	return 0
}

func (x *ProductGroup) GetReturnConfiguration() string {
	if x != nil && x.ReturnConfiguration != nil {
		return *x.ReturnConfiguration
	}
	return ""
}

func (x *ProductGroup) GetExchangeConfiguration() string {
	if x != nil && x.ExchangeConfiguration != nil {
		return *x.ExchangeConfiguration
	}
	return ""
}

func (x *ProductGroup) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *ProductGroup) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return ""
}

type GetMeasurementUnitsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMeasurementUnitsRequest) Reset() {
	*x = GetMeasurementUnitsRequest{}
	mi := &file_proto_catalogue_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeasurementUnitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeasurementUnitsRequest) ProtoMessage() {}

func (x *GetMeasurementUnitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalogue_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeasurementUnitsRequest.ProtoReflect.Descriptor instead.
func (*GetMeasurementUnitsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalogue_product_proto_rawDescGZIP(), []int{6}
}

func (x *GetMeasurementUnitsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetMeasurementUnitsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MeasurementUnits []*MeasurementUnit     `protobuf:"bytes,1,rep,name=measurement_units,json=measurementUnits,proto3" json:"measurement_units,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMeasurementUnitsResponse) Reset() {
	*x = GetMeasurementUnitsResponse{}
	mi := &file_proto_catalogue_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeasurementUnitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeasurementUnitsResponse) ProtoMessage() {}

func (x *GetMeasurementUnitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalogue_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeasurementUnitsResponse.ProtoReflect.Descriptor instead.
func (*GetMeasurementUnitsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalogue_product_proto_rawDescGZIP(), []int{7}
}

func (x *GetMeasurementUnitsResponse) GetMeasurementUnits() []*MeasurementUnit {
	if x != nil {
		return x.MeasurementUnits
	}
	return nil
}

type MeasurementUnit struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UnitId           string                 `protobuf:"bytes,1,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ParentUnitId     *string                `protobuf:"bytes,3,opt,name=parent_unit_id,json=parentUnitId,proto3,oneof" json:"parent_unit_id,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	PrintName        string                 `protobuf:"bytes,5,opt,name=print_name,json=printName,proto3" json:"print_name,omitempty"`
	Description      string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	IsUneditable     bool                   `protobuf:"varint,7,opt,name=is_uneditable,json=isUneditable,proto3" json:"is_uneditable,omitempty"`
	IsPrincipalUnit  bool                   `protobuf:"varint,8,opt,name=is_principal_unit,json=isPrincipalUnit,proto3" json:"is_principal_unit,omitempty"`
	ConversionFactor *string                `protobuf:"bytes,9,opt,name=conversion_factor,json=conversionFactor,proto3,oneof" json:"conversion_factor,omitempty"`
	CreatedAtLocal   *string                `protobuf:"bytes,10,opt,name=created_at_local,json=createdAtLocal,proto3,oneof" json:"created_at_local,omitempty"`
	CreatedAtUtc     *string                `protobuf:"bytes,11,opt,name=created_at_utc,json=createdAtUtc,proto3,oneof" json:"created_at_utc,omitempty"`
	UpdatedAtLocal   *string                `protobuf:"bytes,12,opt,name=updated_at_local,json=updatedAtLocal,proto3,oneof" json:"updated_at_local,omitempty"`
	UpdatedAtUtc     *string                `protobuf:"bytes,13,opt,name=updated_at_utc,json=updatedAtUtc,proto3,oneof" json:"updated_at_utc,omitempty"`
	IsActive         int32                  `protobuf:"varint,14,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DemoMode         bool                   `protobuf:"varint,15,opt,name=demo_mode,json=demoMode,proto3" json:"demo_mode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MeasurementUnit) Reset() {
	*x = MeasurementUnit{}
	mi := &file_proto_catalogue_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurementUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementUnit) ProtoMessage() {}

func (x *MeasurementUnit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalogue_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementUnit.ProtoReflect.Descriptor instead.
func (*MeasurementUnit) Descriptor() ([]byte, []int) {
	return file_proto_catalogue_product_proto_rawDescGZIP(), []int{8}
}

func (x *MeasurementUnit) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *MeasurementUnit) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *MeasurementUnit) GetParentUnitId() string {
	if x != nil && x.ParentUnitId != nil {
		return *x.ParentUnitId
	}
	return ""
}

func (x *MeasurementUnit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MeasurementUnit) GetPrintName() string {
	if x != nil {
		return x.PrintName
	}
	return ""
}

func (x *MeasurementUnit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MeasurementUnit) GetIsUneditable() bool {
	if x != nil {
		return x.IsUneditable
	}
	return false
}

func (x *MeasurementUnit) GetIsPrincipalUnit() bool {
	if x != nil {
		return x.IsPrincipalUnit
	}
	return false
}

func (x *MeasurementUnit) GetConversionFactor() string {
	if x != nil && x.ConversionFactor != nil {
		return *x.ConversionFactor
	}
	return ""
}

func (x *MeasurementUnit) GetCreatedAtLocal() string {
	if x != nil && x.CreatedAtLocal != nil {
		return *x.CreatedAtLocal
	}
	return ""
}

func (x *MeasurementUnit) GetCreatedAtUtc() string {
	if x != nil && x.CreatedAtUtc != nil {
		return *x.CreatedAtUtc
	}
	return ""
}

func (x *MeasurementUnit) GetUpdatedAtLocal() string {
	if x != nil && x.UpdatedAtLocal != nil {
		return *x.UpdatedAtLocal
	}
	return ""
}

func (x *MeasurementUnit) GetUpdatedAtUtc() string {
	if x != nil && x.UpdatedAtUtc != nil {
		return *x.UpdatedAtUtc
	}
	return ""
}

func (x *MeasurementUnit) GetIsActive() int32 {
	if x != nil {
		return x.IsActive
	}
	return 0
}

func (x *MeasurementUnit) GetDemoMode() bool {
	if x != nil {
		return x.DemoMode
	}
	return false
}

var File_proto_catalogue_product_proto protoreflect.FileDescriptor

const file_proto_catalogue_product_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/catalogue/product.proto\x12\tcatalogue\"c\n" +
	"\x17GetProductsByIDsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1f\n" +
	"\vproduct_ids\x18\x02 \x03(\tR\n" +
	"productIds\"J\n" +
	"\x18GetProductsByIDsResponse\x12.\n" +
	"\bproducts\x18\x01 \x03(\v2\x12.catalogue.ProductR\bproducts\"\xbe\x12\n" +
	"\aProduct\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12!\n" +
	"\fproduct_type\x18\x04 \x01(\tR\vproductType\x120\n" +
	"\x11short_description\x18\x05 \x01(\tH\x00R\x10shortDescription\x88\x01\x01\x12.\n" +
	"\x10long_description\x18\x06 \x01(\tH\x01R\x0flongDescription\x88\x01\x01\x12\x16\n" +
	"\x06images\x18\a \x03(\tR\x06images\x12$\n" +
	"\vcolour_code\x18\b \x01(\tH\x02R\n" +
	"colourCode\x88\x01\x01\x123\n" +
	"\x13measurement_unit_id\x18\t \x01(\tH\x03R\x11measurementUnitId\x88\x01\x01\x123\n" +
	"\x13operational_unit_id\x18\n" +
	" \x01(\tH\x04R\x11operationalUnitId\x88\x01\x01\x12+\n" +
	"\x0eclassification\x18\v \x01(\tH\x05R\x0eclassification\x88\x01\x01\x12+\n" +
	"\x12is_sellable_on_pos\x18\f \x01(\bR\x0fisSellableOnPos\x124\n" +
	"\x16allow_variable_pricing\x18\r \x01(\bR\x14allowVariablePricing\x120\n" +
	"\x14price_includes_taxes\x18\x0e \x01(\bR\x12priceIncludesTaxes\x122\n" +
	"\x15default_selling_price\x18\x0f \x01(\x01R\x13defaultSellingPrice\x120\n" +
	"\x14enable_product_group\x18\x10 \x01(\bR\x12enableProductGroup\x120\n" +
	"\x11pricing_attribute\x18\x11 \x01(\tH\x06R\x10pricingAttribute\x88\x01\x01\x120\n" +
	"\x14is_inventory_managed\x18\x12 \x01(\bR\x12isInventoryManaged\x12\x1d\n" +
	"\abarcode\x18\x13 \x01(\tH\aR\abarcode\x88\x01\x01\x12\x15\n" +
	"\x03sku\x18\x14 \x01(\tH\bR\x03sku\x88\x01\x01\x12*\n" +
	"\x0edimension_unit\x18\x15 \x01(\tH\tR\rdimensionUnit\x88\x01\x01\x12*\n" +
	"\x0epackaging_info\x18\x16 \x01(\tH\n" +
	"R\rpackagingInfo\x88\x01\x01\x12A\n" +
	"\x1ainventory_reduction_method\x18\x17 \x01(\tH\vR\x18inventoryReductionMethod\x88\x01\x01\x12 \n" +
	"\trecipe_id\x18\x18 \x01(\tH\fR\brecipeId\x88\x01\x01\x12>\n" +
	"\x19default_stock_alert_level\x18\x19 \x01(\x05H\rR\x16defaultStockAlertLevel\x88\x01\x01\x12<\n" +
	"\x18default_safe_stock_level\x18\x1a \x01(\x05H\x0eR\x15defaultSafeStockLevel\x88\x01\x01\x12/\n" +
	"\x11country_of_origin\x18\x1b \x01(\tH\x0fR\x0fcountryOfOrigin\x88\x01\x01\x12%\n" +
	"\fhsn_sac_code\x18\x1c \x01(\tH\x10R\n" +
	"hsnSacCode\x88\x01\x01\x128\n" +
	"\x19disable_sales_on_no_stock\x18\x1d \x01(\bR\x15disableSalesOnNoStock\x12@\n" +
	"\x1ddisable_sales_on_stock_expiry\x18\x1e \x01(\bR\x19disableSalesOnStockExpiry\x12,\n" +
	"\x0freturn_exchange\x18\x1f \x01(\tH\x11R\x0ereturnExchange\x88\x01\x01\x12#\n" +
	"\n" +
	"attributes\x18  \x01(\tH\x12R\n" +
	"attributes\x88\x01\x01\x12)\n" +
	"\rrelationships\x18! \x01(\tH\x13R\rrelationships\x88\x01\x01\x125\n" +
	"\x14item_type_attributes\x18\" \x01(\tH\x14R\x12itemTypeAttributes\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18# \x01(\tH\x15R\tcreatedBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_by\x18$ \x01(\tH\x16R\tupdatedBy\x88\x01\x01\x12(\n" +
	"\x10created_at_local\x18% \x01(\tR\x0ecreatedAtLocal\x12$\n" +
	"\x0ecreated_at_utc\x18& \x01(\tR\fcreatedAtUtc\x12-\n" +
	"\x10updated_at_local\x18' \x01(\tH\x17R\x0eupdatedAtLocal\x88\x01\x01\x12)\n" +
	"\x0eupdated_at_utc\x18( \x01(\tH\x18R\fupdatedAtUtc\x88\x01\x01\x12\x1b\n" +
	"\tdemo_mode\x18) \x01(\bR\bdemoMode\x12\x1b\n" +
	"\tis_active\x18* \x01(\x05R\bisActiveB\x14\n" +
	"\x12_short_descriptionB\x13\n" +
	"\x11_long_descriptionB\x0e\n" +
	"\f_colour_codeB\x16\n" +
	"\x14_measurement_unit_idB\x16\n" +
	"\x14_operational_unit_idB\x11\n" +
	"\x0f_classificationB\x14\n" +
	"\x12_pricing_attributeB\n" +
	"\n" +
	"\b_barcodeB\x06\n" +
	"\x04_skuB\x11\n" +
	"\x0f_dimension_unitB\x11\n" +
	"\x0f_packaging_infoB\x1d\n" +
	"\x1b_inventory_reduction_methodB\f\n" +
	"\n" +
	"_recipe_idB\x1c\n" +
	"\x1a_default_stock_alert_levelB\x1b\n" +
	"\x19_default_safe_stock_levelB\x14\n" +
	"\x12_country_of_originB\x0f\n" +
	"\r_hsn_sac_codeB\x12\n" +
	"\x10_return_exchangeB\r\n" +
	"\v_attributesB\x10\n" +
	"\x0e_relationshipsB\x17\n" +
	"\x15_item_type_attributesB\r\n" +
	"\v_created_byB\r\n" +
	"\v_updated_byB\x13\n" +
	"\x11_updated_at_localB\x11\n" +
	"\x0f_updated_at_utc\"s\n" +
	"\x1cGetProductGroupsByIDsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12*\n" +
	"\x11product_group_ids\x18\x02 \x03(\tR\x0fproductGroupIds\"_\n" +
	"\x1dGetProductGroupsByIDsResponse\x12>\n" +
	"\x0eproduct_groups\x18\x01 \x03(\v2\x17.catalogue.ProductGroupR\rproductGroups\"\xb2\t\n" +
	"\fProductGroup\x12(\n" +
	"\x10product_group_id\x18\x01 \x01(\tR\x0eproductGroupId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12,\n" +
	"\x12product_group_name\x18\x03 \x01(\tR\x10productGroupName\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tR\tproductId\x120\n" +
	"\x11short_description\x18\x05 \x01(\tH\x00R\x10shortDescription\x88\x01\x01\x12.\n" +
	"\x10long_description\x18\x06 \x01(\tH\x01R\x0flongDescription\x88\x01\x01\x12\x1b\n" +
	"\tpg_status\x18\a \x01(\tR\bpgStatus\x12\x16\n" +
	"\x06images\x18\b \x03(\tR\x06images\x12\"\n" +
	"\n" +
	"pg_barcode\x18\t \x01(\tH\x02R\tpgBarcode\x88\x01\x01\x12\x1a\n" +
	"\x06pg_sku\x18\n" +
	" \x01(\tH\x03R\x05pgSku\x88\x01\x01\x122\n" +
	"\x12manufacturing_date\x18\v \x01(\tH\x04R\x11manufacturingDate\x88\x01\x01\x12$\n" +
	"\vexpiry_date\x18\f \x01(\tH\x05R\n" +
	"expiryDate\x88\x01\x01\x12\"\n" +
	"\n" +
	"shelf_life\x18\r \x01(\x05H\x06R\tshelfLife\x88\x01\x01\x12'\n" +
	"\rcost_per_unit\x18\x0e \x01(\x01H\aR\vcostPerUnit\x88\x01\x01\x12@\n" +
	"\x19fulfillment_configuration\x18\x0f \x01(\tH\bR\x18fulfillmentConfiguration\x88\x01\x01\x12#\n" +
	"\n" +
	"attributes\x18\x10 \x01(\tH\tR\n" +
	"attributes\x88\x01\x01\x12%\n" +
	"\fsell_by_date\x18\x11 \x01(\tH\n" +
	"R\n" +
	"sellByDate\x88\x01\x01\x12\x15\n" +
	"\x03mrp\x18\x12 \x01(\x01H\vR\x03mrp\x88\x01\x01\x126\n" +
	"\x14return_configuration\x18\x13 \x01(\tH\fR\x13returnConfiguration\x88\x01\x01\x12:\n" +
	"\x16exchange_configuration\x18\x14 \x01(\tH\rR\x15exchangeConfiguration\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\x15 \x01(\tH\x0eR\tcreatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\tH\x0fR\tupdatedAt\x88\x01\x01B\x14\n" +
	"\x12_short_descriptionB\x13\n" +
	"\x11_long_descriptionB\r\n" +
	"\v_pg_barcodeB\t\n" +
	"\a_pg_skuB\x15\n" +
	"\x13_manufacturing_dateB\x0e\n" +
	"\f_expiry_dateB\r\n" +
	"\v_shelf_lifeB\x10\n" +
	"\x0e_cost_per_unitB\x1c\n" +
	"\x1a_fulfillment_configurationB\r\n" +
	"\v_attributesB\x0f\n" +
	"\r_sell_by_dateB\x06\n" +
	"\x04_mrpB\x17\n" +
	"\x15_return_configurationB\x19\n" +
	"\x17_exchange_configurationB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_at\"E\n" +
	"\x1aGetMeasurementUnitsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"f\n" +
	"\x1bGetMeasurementUnitsResponse\x12G\n" +
	"\x11measurement_units\x18\x01 \x03(\v2\x1a.catalogue.MeasurementUnitR\x10measurementUnits\"\xbd\x05\n" +
	"\x0fMeasurementUnit\x12\x17\n" +
	"\aunit_id\x18\x01 \x01(\tR\x06unitId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12)\n" +
	"\x0eparent_unit_id\x18\x03 \x01(\tH\x00R\fparentUnitId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"print_name\x18\x05 \x01(\tR\tprintName\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12#\n" +
	"\ris_uneditable\x18\a \x01(\bR\fisUneditable\x12*\n" +
	"\x11is_principal_unit\x18\b \x01(\bR\x0fisPrincipalUnit\x120\n" +
	"\x11conversion_factor\x18\t \x01(\tH\x01R\x10conversionFactor\x88\x01\x01\x12-\n" +
	"\x10created_at_local\x18\n" +
	" \x01(\tH\x02R\x0ecreatedAtLocal\x88\x01\x01\x12)\n" +
	"\x0ecreated_at_utc\x18\v \x01(\tH\x03R\fcreatedAtUtc\x88\x01\x01\x12-\n" +
	"\x10updated_at_local\x18\f \x01(\tH\x04R\x0eupdatedAtLocal\x88\x01\x01\x12)\n" +
	"\x0eupdated_at_utc\x18\r \x01(\tH\x05R\fupdatedAtUtc\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\x0e \x01(\x05R\bisActive\x12\x1b\n" +
	"\tdemo_mode\x18\x0f \x01(\bR\bdemoModeB\x11\n" +
	"\x0f_parent_unit_idB\x14\n" +
	"\x12_conversion_factorB\x13\n" +
	"\x11_created_at_localB\x11\n" +
	"\x0f_created_at_utcB\x13\n" +
	"\x11_updated_at_localB\x11\n" +
	"\x0f_updated_at_utc2\xbf\x02\n" +
	"\x0eProductService\x12[\n" +
	"\x10GetProductsByIDs\x12\".catalogue.GetProductsByIDsRequest\x1a#.catalogue.GetProductsByIDsResponse\x12j\n" +
	"\x15GetProductGroupsByIDs\x12'.catalogue.GetProductGroupsByIDsRequest\x1a(.catalogue.GetProductGroupsByIDsResponse\x12d\n" +
	"\x13GetMeasurementUnits\x12%.catalogue.GetMeasurementUnitsRequest\x1a&.catalogue.GetMeasurementUnitsResponseB%Z#qb-accounting/internal/proto/catalogueb\x06proto3"

var (
	file_proto_catalogue_product_proto_rawDescOnce sync.Once
	file_proto_catalogue_product_proto_rawDescData []byte
)

func file_proto_catalogue_product_proto_rawDescGZIP() []byte {
	file_proto_catalogue_product_proto_rawDescOnce.Do(func() {
		file_proto_catalogue_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_catalogue_product_proto_rawDesc), len(file_proto_catalogue_product_proto_rawDesc)))
	})
	return file_proto_catalogue_product_proto_rawDescData
}

var file_proto_catalogue_product_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_catalogue_product_proto_goTypes = []any{
	(*GetProductsByIDsRequest)(nil),       // 0: catalogue.GetProductsByIDsRequest
	(*GetProductsByIDsResponse)(nil),      // 1: catalogue.GetProductsByIDsResponse
	(*Product)(nil),                       // 2: catalogue.Product
	(*GetProductGroupsByIDsRequest)(nil),  // 3: catalogue.GetProductGroupsByIDsRequest
	(*GetProductGroupsByIDsResponse)(nil), // 4: catalogue.GetProductGroupsByIDsResponse
	(*ProductGroup)(nil),                  // 5: catalogue.ProductGroup
	(*GetMeasurementUnitsRequest)(nil),    // 6: catalogue.GetMeasurementUnitsRequest
	(*GetMeasurementUnitsResponse)(nil),   // 7: catalogue.GetMeasurementUnitsResponse
	(*MeasurementUnit)(nil),               // 8: catalogue.MeasurementUnit
}
var file_proto_catalogue_product_proto_depIdxs = []int32{
	2, // 0: catalogue.GetProductsByIDsResponse.products:type_name -> catalogue.Product
	5, // 1: catalogue.GetProductGroupsByIDsResponse.product_groups:type_name -> catalogue.ProductGroup
	8, // 2: catalogue.GetMeasurementUnitsResponse.measurement_units:type_name -> catalogue.MeasurementUnit
	0, // 3: catalogue.ProductService.GetProductsByIDs:input_type -> catalogue.GetProductsByIDsRequest
	3, // 4: catalogue.ProductService.GetProductGroupsByIDs:input_type -> catalogue.GetProductGroupsByIDsRequest
	6, // 5: catalogue.ProductService.GetMeasurementUnits:input_type -> catalogue.GetMeasurementUnitsRequest
	1, // 6: catalogue.ProductService.GetProductsByIDs:output_type -> catalogue.GetProductsByIDsResponse
	4, // 7: catalogue.ProductService.GetProductGroupsByIDs:output_type -> catalogue.GetProductGroupsByIDsResponse
	7, // 8: catalogue.ProductService.GetMeasurementUnits:output_type -> catalogue.GetMeasurementUnitsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_catalogue_product_proto_init() }
func file_proto_catalogue_product_proto_init() {
	if File_proto_catalogue_product_proto != nil {
		return
	}
	file_proto_catalogue_product_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_catalogue_product_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_catalogue_product_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_catalogue_product_proto_rawDesc), len(file_proto_catalogue_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_catalogue_product_proto_goTypes,
		DependencyIndexes: file_proto_catalogue_product_proto_depIdxs,
		MessageInfos:      file_proto_catalogue_product_proto_msgTypes,
	}.Build()
	File_proto_catalogue_product_proto = out.File
	file_proto_catalogue_product_proto_goTypes = nil
	file_proto_catalogue_product_proto_depIdxs = nil
}
